packages/eslint-config-humanmade/.eslintrc.yml

Fixes space-unary-ops

---

packages/eslint-config-humanmade/package.json

Bump ESLint config version

---

composer.json

The current version breaks under phpcs 3.x

Update wpcs to the latest version

---

composer.json
packages/eslint-config-humanmade/package.json

Mainly just need to bump the ESLint package version, since Packagist follows tags.

Bump to 0.3.0

---

packages/eslint-config-humanmade/.eslintrc.yml

Enforce spaces inside JSX curly braces

Enforce spaces inside jsx curly braces

---

HM/ruleset.xml

Allow multiple declarations in use

---

readme.md

just a cosmetic issue with the readme

fix yaml formatting

---

HM/ruleset.xml

See https://github.com/humanmade/coding-standards/issues/61.

Remove alignment of equals rule

---

publish.sh

@mikeselander brought to my attention that I never committed this. Whoops!

Add publish script

---

CHANGELOG.md

Minor adjustments and inclusions for the CHANGELOG.

Update CHANGELOG file

---

packages/eslint-config-humanmade/readme.md

This adds a simple shortcut for installing peerdeps.

Add npx install-peerdeps documentation

---

CHANGELOG.md
packages/eslint-config-humanmade/fixtures/fail/jsx-curly-newline.jsx
packages/eslint-config-humanmade/fixtures/pass/jsx-curly-newline.jsx
packages/eslint-config-humanmade/index.js

Fixes https://github.com/humanmade/coding-standards/issues/171

Enforce curly newlines jsx

---

CHANGELOG.md
packages/eslint-config-humanmade/fixtures/fail/jsx-boolean-value.jsx
packages/eslint-config-humanmade/fixtures/pass/jsx-boolean-value.jsx
packages/eslint-config-humanmade/index.js

As discussed on https://github.com/humanmade/coding-standards/issues/182

Add ESLint rule for jsx boolean values

---

packages/eslint-config-humanmade/readme.md

Nothing much else to say! Out of the box, the eslint package will mostly work fine, but it will throw errors some TypeScript-specific syntax. This fixes that!

Add typescript documentation

---

HM/ruleset.xml

Exclude missing package tag file comment rule

---

.gitignore

Adds some rules to gitignore to clean up `git status` after having deployed.

Add built directories to gitignore

---

.travis.yml

This PR seeks to add caching for Composer and Node.js packages

Add caching to Travis CI for Composer and Node.js

---

CHANGELOG.md
packages/eslint-config-humanmade/package.json

See https://github.com/humanmade/coding-standards/issues/215

Include all eslint plugins in peer dependencies

---

packages/eslint-config-humanmade/readme.md

Update ESLint Install Instructions

---

composer.json

Backport Composer installer package update to the 1.0 branch

---

packages/eslint-config-humanmade/fixtures/fail/template-curly-spacing.js
packages/eslint-config-humanmade/fixtures/pass/template-curly-spacing.js
packages/eslint-config-humanmade/index.js

Require spaces in template strings

---

README.md
package-lock.json
package.json
packages/stylelint-config/package.json
packages/stylelint-config/readme.md

Various Minor Meta Updates
- d7a90d1 Use travis-ci.com, travis-ci.org was retired June 15th 2021
- 9bc4741 Update npm badge links in README.md
- 50e6bd6 Use correctly scoped @humanmade/stylelint-config package name in st…
- 14168e2 Update npm-package-json-lint to v5.1.0
- c4d23e1 Update lerna to v4.0.0 
- ae6f396 Use correct repository directory in stylelint-config package
- b737924 Update stylelint to use peerDependencies instead of `devDependenc…

Minor Meta Updates

---

package-lock.json

Update _root_ `package-lock.json` via `npm audit fix`

Update _root_ `package-lock.json` via `npm audit fix`

---

packages/eslint-config-humanmade/package.json

Add `eslint` v8 `peerDependencies` support

Add `eslint` v8 `peerDependencies` support

---

.travis.yml
package-lock.json
package.json
packages/stylelint-config/fixtures/fail/bad-bem-syntax.css
packages/stylelint-config/fixtures/fail/max-nesting-depth.scss
packages/stylelint-config/fixtures/fail/no-color-named.css
packages/stylelint-config/fixtures/pass/style.css
packages/stylelint-config/fixtures/pass/style.scss
packages/stylelint-config/fixtures/test-lint-config.js
packages/stylelint-config/package-lock.json
packages/stylelint-config/package.json

Add some basic tests for styles. Follows similar setup to eslint tests. Can increase coverage in future. 
@tomjn Already did a PR for updating to the latest config already: https://github.com/humanmade/coding-standards/pull/275. Some tests could be a nice way to help test this.

Add stylelint tests

---

HM/ruleset.xml

Ease up on the PHP DOM* objects and methods.
Credit to @ntwb for the first iteration of this.

Update ruleset.xml for PHP DOM*
