humanmade/coding-standards

- packages/eslint-config-humanmade/.eslintrc.yml
Allow spaces inside brackets of array literals that contain a single element.
`"singleValue": false` makes an exception for `[1]` and similar, so removing it makes the spacing consistent. See [documentation](http://eslint.org/docs/rules/array-bracket-spacing).
> Always allow spaces inside arrays

- packages/eslint-config-humanmade/.eslintrc.yml
This code:
```
export default function cache( state = {}, action ) {
switch ( action.type ) {
case 'UPDATE_CACHE':
return Object.assign( {}, state, action.payload );
default:
return state;
}
}
```
currently produces the following error:
```
3:3  error  Expected indentation of 1 tab but found 2   indent
4:4  error  Expected indentation of 2 tabs but found 3  indent
6:3  error  Expected indentation of 1 tab but found 2   indent
7:4  error  Expected indentation of 2 tabs but found 3  indent
```
To pass the linting, this would have to be written like this:
```
export default function cache( state = {}, action ) {
switch ( action.type ) {
case 'UPDATE_CACHE':
return Object.assign( {}, state, action.payload );
default:
return state;
}
}
```
This is because the `SwitchCase` indent level is not …
> Whitelist 1 level of indentation in `switch` cases.

- HM/Sniffs/Layout/OrderSniff.php
- HM/Tests/Layout/OrderUnitTest.inc
- HM/Tests/Layout/OrderUnitTest.php
The order sniff was incorrectly picking up the use keyword in nested lambda functions. This fixes it and adds a unit test for the sniff.
cc @rmccue
> Fix order sniff, add tests

- .travis.yml
- readme.md
OS projects should use travis for running tests. This is the basic test harness for running code sniffer tests.
> Adding travis CI

- HM/Sniffs/Files/NamespaceDirectoryNameSniff.php
`DIRECTORY_SEPARATOR` is equal to `\` on Windows, but the code uses a hard coded `/inc` to do its checks.
This fix normalizes `$directory` when running on Windows.
> Fix rule when runing on Windows

- packages/eslint-config-humanmade/.eslintrc.yml
> Require space after negation("!") operator

- packages/eslint-config-humanmade/.eslintrc.yml
This was meant to allow this:
```js
var x = { 'y': {
// ...
}};
```
But as it turns out, it's utterly useless, and that was a terrible idea anyway.
Fixes #18.
> Require spaces for objects inside objects

- HM/ruleset.xml
I also don't like most of the VIP rules so personally think we would be better to select specific ones we wanted rather than importing all theirs.
> Remove VIP rule for adminbar

- HM/Sniffs/Debug/ESLintSniff.php
This ensures `eslint` uses our package regardless of installation status.
> Set NODE_PATH to make our eslint package available

- HM/ruleset.xml
This avoids the JS-in-PHP parser thinking that `<Component>` is actually comparison operators and complaining endlessly about it.
> Exclude space checks from JS files

- HM/Sniffs/Classes/OnlyClassInFileSniff.php
- HM/Sniffs/Debug/ESLintSniff.php
- HM/Sniffs/Files/ClassFileNameSniff.php
- HM/Sniffs/Files/FunctionFileNameSniff.php
- HM/Sniffs/Files/NamespaceDirectoryNameSniff.php
- HM/Sniffs/Functions/NamespacedFunctionsSniff.php
- HM/Sniffs/Layout/OrderSniff.php
- HM/Sniffs/Namespaces/NoLeadingSlashOnUseSniff.php
- composer.json
This gets us a bunch o' new stuff, including:
* Parallel checks with `--parallel=10`
* Caching between runs with `--cache`
* `--report=code` to show the errored line in context
* `-m` to suppress error message gathering to save memory
* Autodetection of phpcs files
* ES6 tokenisation
* Progress with `-p`
[All changes](https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.0.0).
> Update phpcs to v3

- composer.json
WPCS [release 0.14.0](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/releases/tag/0.14.0) modified the WordPress VIP sniffs to no longer complain about uncached term functions like `get_term_by()`.
These functions used to be uncached, and you had to use VIP's alternatives. But since 4.8, they use a `WP_Term_Query` internally.
I'd like to update this, as we're using the Core functions get lots of false positives for this. We're using `dev-master`, so no need for a new release.
> Update WPCS to ^0.14.0.

- packages/eslint-config-humanmade/index.js
- packages/eslint-config-humanmade/package.json
This upgrades eslint, adds the “consistent” option for single property object sanity, and adjusts the rules and config file so that it passes its own definitions.
> Make index pass its own rules

- HM/bootstrap.php
- HM/ruleset.xml
- readme.md
To match `.eslintignore` and `.gitignore`, we should support a `.phpcsignore`. This removes one of the big reasons you'd need a `phpcs.ruleset.xml` in many repos.
See https://github.com/squizlabs/PHP_CodeSniffer/issues/1884
> Add support for a .phpcsignore file

- HM/ruleset.xml
Supersedes #48, but uses rule configuration rather than ignoring the rule output.
> Exclude filesystem groups from checks

- HM/ruleset.xml
Fixes #43. This allows either `<?php inline() ?>` or `<?php inline(); ?>` per personal preference.
> Allow inline statements to drop semicolons

- packages/eslint-config-humanmade/index.js
Changes the `object-curly-newline` rule to remove the `minProperties` restriction on object patterns (i.e. destructuring assignment) and imports. This makes newlines optional for both, but still enforces consistency.
Fixes #58.
> Adjust object rules for destructuring

- HM/ruleset.xml
Right now, the alignment check will force you to dealign if the line would be longer than 60 characters long. 🙄  This is set in the [WordPress-Core](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/06f6d5c0f7588601c2823dd7abb7e9022fd658dc/WordPress-Core/ruleset.xml#L83-L88) standard.
PR changes it back to the default (in code) of 1000 columns, aka always align.
See https://github.com/humanmade/hm-stack/pull/448 for where this was failing.
> Ignore line length when checking array alignment

- packages/eslint-config-humanmade/index.js
- packages/eslint-config-humanmade/package.json
Fixes #56 
The update process to the latest available versions of all packages was generally straightforward, excepting one new jsx-a11y rule that the react app configuration does not yet support. I worked around this by swapping the deprecated rule out for the new one in our own config.
This could use some more testing in real projects, so anybody who can `npm link` this in and give it a run, please report your findings!
> Update ESLint config peer dependencies

- composer.json
phpcs has a pretty loose interpretation of semantic versioning, so we need to use the tilde operator rather than the caret operator. This ensures that it's locked to 3.2.x rather than 3.x.x.
Fixes #79.
> Lock the phpcs minor version

- HM/Sniffs/Debug/ESLintSniff.php
- readme.md
This updates the root-level README documentation around usage of ESLint. The existing README referenced an incorrect path to the project's `.eslintrc` file, which was removed from the root directory in #54. #54 also removed the ability to run ESLint via phpcs (it is preferable to run eslint directly via npm packages, or to use linter-bot).
This PR updates the documentation around how to reference the `.eslintrc` file (renamed from `.eslintrc.yml` in #40) if you choose to use the configuration from the composer package in lieu of installing directly via npm.
Thank you @mattheu for raising this issue
> Update README to reflect updated .eslintrc location

- packages/eslint-config-humanmade/index.js
See https://eslint.org/docs/user-guide/migrating-to-5.0.0#experimental-object-rest-spread
`(node:1244) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "humanmade")`
> use ecmaVersion 2018

- readme.md
The readme for requiring our coding standards gave a command that included them as a production dependency. The standard set should only be included in a development environment so adding the `--dev` flag to the command to place it in the appropriate list.
> Add --dev flag to Composer HM standards inclusion

- HM/ruleset.xml
This is a genuinely useful function for reporting errors in production. Due to how the WordPress sniff is written, we can't use the same style of excluding as the other dissalowed functions, as there's others we want under the "error_log" group.
> Allow trigger_error

- packages/stylelint-config-humanmade/stylelint.json
Stylelint is currently (via a parent config, I assume) requiring that _no_ quotes be used within the CSS `url()` function. However, using `url()` without quotes requires special escaping and the potential for forgetting to escape a special character exists, making use with quotes just a little bit safer. I propose that we require quotes in URLs for consistency and ease of use.
Ref: https://drafts.csswg.org/css-values-3/#urls
This PR defines this rule to "always" to match the current spec.
> Stylelint: Define `function-url-quotes`

- packages/stylelint-config-humanmade/stylelint.json
As discussed in #104, requiring that `ms` units be used for timing durations and ensure that `px` values cannot be used for font-sizes.
Have I missed any timing durations in this list?
cc @humanmade/frontend for thoughts/review.
> Unit Listing Requirements

- packages/stylelint-config-humanmade/stylelint.json
Adds a [`media-feature-parentheses-space-inside` rule](https://stylelint.io/user-guide/rules/media-feature-parentheses-space-inside/) to enforce spaces inside media queries.
The purpose of this change is for consistency with the rule `function-parentheses-space-inside`. I noticed it was missing when @kucrut picked up an error (mine) on a client project.
cc @humanmade/frontend
> Enforce spaces inside media queries.

- composer.json
- tests/FixtureTests.php
PHPCS 3.3 included a plethora of useful bugfixes and improvements and will improve the Linter sniffing for several clients.
Reference: https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.3.0 for a more exhaustive list of bugfixes.
Resolves #70 
Resolves #110
> Update PHPCS to v3.4

- composer.json
For the purposes of Composer, these coding standards are a PHPCS standard and currently we've only marked this as a "project". We should be more specific about the type of library this is for sorting and path-directing purposes.
> Set Composer Library Type

- packages/eslint-config-humanmade/package.json
It's that time again: time to upgrade our peer dependencies! This does bump the eslint version, so if @joehoyle @rmccue I acknowledge we may want to exercise more caution and hold off for a bit. That said, I'm in favor of testing this and then releasing as `0.6.0` to permit projects to take advantage of the changes. Because of how semver handles <1.0 versions a `0.6.0` release won't affect any projects currently using `^0.5.0`, making the change strictly opt-in and forward-facing.
The other benefit is that there was a conflict between `eslint-config-react-app` and `eslint-plugin-jsx-a11y`, which the latest bump to the React App config mercifully resolves.
Resolves #56
> Upgrade peer dependency versions

- packages/eslint-config-humanmade/index.js
As @ntwb pointed out in #101, we should now remove the `href-no-hash` rule as `eslint-config-react-app` updated their dependencies quite a while ago so this rule should no longer be needed.
Ref: https://github.com/facebook/create-react-app/pull/2690
⚠️ this is built on top of #101 and that will need to be merged first.
> Remove `href-no-hash` Rule

- packages/eslint-config-humanmade/readme.md
- packages/stylelint-config-humanmade/readme.md
We've had a line recommending usage via Composer in both NPM packages but this it no longer recommended. Removing for future users.
> Remove Composer References in NPM Packages

- packages/eslint-config-humanmade/index.js
Currently this code is allowed. I think we should enforce a space inside curly braces for children.
```
<div>
{children}
{foo && (
<p>Foo</p>
)}
</div>
```
Expected:
```
<div>
{ children }
{ foo && (
<p>Foo</p>
) }
</div>
```
> Require space in curly braces for children

- composer.json
Adding VIP phpcs standards so we can utilize them within `hm-linter`.
> Adding VIP phpcs standards

- HM/ruleset.xml
- composer.json
In WPCS 1.1.0, the `allowMultipleArguments` property from `PEAR.Functions.FunctionCallSignature` was disallowed, causing our tests to fail and existing behavior to be altered. 
I re-allowed this to restore expected behavior and updated Composer to more explicitly show which version we are on (`^1.0.0` was already giving us 1.2.1, just without the explicit declaration).
We can easily turn this back off if we decide to alter the behavior in the future. I believe this to be the only "breaking"/expectation-changing behavior from WPCS 1.0.0 -> 1.2.0.
> Restore `allowMultipleArguments`

- CHANGELOG.md
- HM/Sniffs/Files/NamespaceDirectoryNameSniff.php
- tests/fixtures/pass/load.php
Per composer packages, we use `load.php`, as `plugin.php` doesn't make sense as the entry point name
> Allow load.php

- CHANGELOG.md
- HM/ruleset.xml
Given we have PHP 7+, we don't need to use wp_json_encode / wp_json_decode. Using the WP alternatives is also not easy in things like SUNRISE or wp-config.php as those functions may not be yet available.
> Allow json_encode / json_decode

- HM/Tests/Classes/OnlyClassInFileUnitTest.php
- HM/Tests/Files/ClassFileNameUnitTest.php
- HM/Tests/Files/FunctionFileNameUnitTest.php
- HM/Tests/Files/NamespaceDirectoryNameUnitTest.php
- HM/Tests/Layout/OrderUnitTest.php
- HM/Tests/Namespaces/NoLeadingSlashOnUseUnitTest.php
- tests/AllSniffs.php
- tests/FixtureTests.php
- tests/bootstrap.php
While debugging #81, I made a series of style fixes that keep the code a bit cleaner and easier to read.
- Removes unused `use` statements
- Moves classes from `\` to `use`
- Defines class variables used by the class
- Adds `@group` definitions for more finite testing
- Defines some constants that should help PHPCS work more intelligently while testing
> Test Suite Improvements

- composer.json
VIP recently updated their standard set, and bumped their linter bot without a warm-up period. This means that we need to bump our version include so that our linter bot can match theirs. 
Ref: https://github.com/Automattic/VIP-Coding-Standards/releases/tag/1.0.0
Note: VIPCS is incompatible with WPCS 2.*, this won't affect most of our projects but could limit who can upgrade when we bump WPCS.
Resolves #136
> Bump VIPCS Dep to 1.0.0

- packages/stylelint-config/package.json
- publish.sh
We're not currently building Stylelint bundles to publish to the Linter bot, which is a required step for Linter Bot to run stylelint. This adds the necessary step to publish and fixes the Stylelint dependencies.
> Add stylelint bundle step to build script

- composer.json
This PR is a pre-cursor to #81 and makes PHPCompatibilityWP available to users of the Linter Bot. This is an incremental improvement only and allows us to provide the package to users without waiting to figure out the test suite problems that are encountered in #81.
This has @tfrommen to thank for this change 👍
> Make PHPCompatibilityWP Available via Composer

- CHANGELOG.md
- packages/stylelint-config/package.json
Bumps the WordPress stylelint rules from v13.0 to v16.0. From what I'm reading the only rule change this brings is to add the [`function-calc-no-invalid`](https://stylelint.io/user-guide/rules/function-calc-no-invalid) rule which is a really nice addition and will only flag erroneous usages of `calc`. Is there anything else worth flagging or worth notifying devs of in these versions @ntwb? 
See the following changelogs for more on the releases.
- https://github.com/WordPress-Coding-Standards/stylelint-config-wordpress/releases
- https://github.com/kristerkari/stylelint-config-recommended-scss/releases
- https://github.com/stylelint/stylelint-config-recommended/releases
Resolves #138
> Bump WordPress stylelint config from v13 to v16

- CHANGELOG.md
- HM/ruleset.xml
- tests/fixtures/pass/inc/namespace.php
- tests/fixtures/pass/tests/namespace.php
We've previously not enforced escaping in our standards set but doing so is important. Here, I add this rule back into our ruleset.
Resolves #102
> Enforce Escaping in PHPCS

- CHANGELOG.md
- packages/eslint-config-humanmade/fixtures/fail/semicolon.js
- packages/eslint-config-humanmade/fixtures/pass/semicolon.js
- packages/eslint-config-humanmade/index.js
Enforce semicolons.
Closes #153
> ESLint Enforce semicolons

- CHANGELOG.md
- packages/stylelint-config/.stylelintrc.json
Fixes #160
Ignore `if`, `elseif` and `else` from the rule `at-rule-empty-line-before` to allow correct formatting of these statements.
> Ignore at-rule line break for if/else/elseif

- CHANGELOG.md
- HM/Sniffs/Whitespace/MultipleEmptyLinesSniff.php
- HM/Tests/Whitespace/MultipleEmptyLinesUnitTest.fail
- HM/Tests/Whitespace/MultipleEmptyLinesUnitTest.php
- HM/Tests/Whitespace/MultipleEmptyLinesUnitTest.success
- HM/ruleset.xml
- tests/fixtures/fail/consecutive-empty-lines.php
- tests/fixtures/fail/consecutive-empty-lines.php.json
This PR copies in a rule to handles multiple empty lines all throughout PHP. I copied this rule in the MediaWiki ruleset as it felt unnecessary to include their whole ruleset for one very small rule and this is a particularly maintainable sniff. I am open to opinions on the approach.
This will detect any empty consecutive lines. It improves on the main Squiz rule as the Squiz rule only detects multiple lines within functions, and not in classes or in general PHP.
Fixes #60
> Add Rule to Detect Consecutive Newlines

- CHANGELOG.md
- tests/FixtureTests.php
**Problem:**
We've been loading any and all standards from our HM ruleset within our fixture tests, but the fixture tests only store errors for our specific standards. Loading in other standards is causing all kinds of false errors such as those seen in #81 and #151. I believe that these errors are related to PHPCS autoloading some classes and then our standard coming in and triggering them to load again. PHPCS runs fine and as expected on the command line, but fails in the test suite for the above hard-to-trace reasons. 
**Solution:**
The Ruleset class offers us the ability to limit the standards loaded to a specific subset so that our tests run only against our custom code. Since we're only recording errors on our custom sniffs, there's little point to loading in all the standards for …
> Limit Fixture Test Standards

- CHANGELOG.md
- packages/stylelint-config/.stylelintrc.json
This PR adds the stylelint [`declaration-no-important`](https://stylelint.io/user-guide/rules/declaration-no-important) rule which disallows usages of `!important` unless a developer specifically adds a exception comment.
Fixes #144
> Disallow Usage of `!important` in CSS

- CHANGELOG.md
- composer.json
3.4.* creates a lot of warnings with PHP 7.4. Switching this, everything looks to still work.
> Update to phpcs 3.5.*

- CHANGELOG.md
- packages/eslint-config-humanmade/package.json
Following @mikeselander comment here: https://github.com/humanmade/linter-bot/pull/112, I need to replicate that PR here
> Make eslint-plugin-sort-destructure-keys eslint plugin available

- HM-Required/ruleset.xml
- HM/Sniffs/Performance/SlowMetaQuerySniff.php
- HM/Sniffs/Performance/SlowOrderBySniff.php
This replaces the blanket rule in WPCS for any meta query with something a lot smarter, allowing any meta queries which are using `EXISTS` or `NOT EXISTS` queries.
It also disallows the use of `meta_value`, `meta_value_num`, and `rand` in `orderby`.
> Add better checks for meta queries

- CHANGELOG.md
- HM/ruleset.xml
- composer.json
Updates WP CS and VIP CS packages to latest versions.
VIP CS rules are now compatible with WP CS 2.*
see https://github.com/Automattic/VIP-Coding-Standards/releases/tag/2.0.0
Resolves #130 
Resolves #148
> Update: WPCS 2.1.1 / VIPCS 2.0.0

- CHANGELOG.md
- HM/ruleset.xml
This includes the WordPress-Docs ruleset by default in PHPCS. 
Note that this has the potential to create a _lot_ of noise on existing projects and we should likely warn people when/if this is merged and deployed.
Fixes #167
> Include WordPress-Docs ruleset in PHPCS

- readme.md
Our readme is still instructing developers to use eslint from Composer, whereas we should be instructing them to use it directly via NPM.
Resolves #90
> Simplify the installation instructions for `eslint` in our readme

- CHANGELOG.md
- HM/ruleset.xml
This PR fixes several issues related to the defaults set in the HM ruleset that define the basepath and main files. These provide easy defaults, but can cause issues in several cases which make our rules unusable.
- Removing `<basepath>`: This value was preventing Visual Studio Code PHPCS extensions from using our ruleset. See #184
- Removing `<file>`: This value was preventing projects from creating an "inclusion" list, forcing them to instead build a "disallow" list instead which is untenable for some projects. See #159
I feel comfortable forcing projects to set these values as they need since PHPCS should really only be setup once on a project.
Paging @jrfnl and @ntwb - do you see any problem with removing these values I might have missed?
> Remove Default `<file>` and `<basepath>` values

- packages/eslint-config-humanmade/index.js
Based on https://github.com/humanmade/coding-standards/issues/75 conversation, this PR adds a new rule to force the React components props to be sorted alphabetically
> Add React sorting props rule

- CHANGELOG.md
- HM/ruleset.xml
Allows us to assign multiple variables in a row.
To test, run `vendor/bin/phpcbf --standard=HM/ruleset.xml example.php` against the following `example.php` file locally.
```php
<?php
$foo = $bar = 'thing';
if ( $foo = get_me_something() ) {
return false;
}
```
The first inline assignment should pass, and the inline conditional should still flag errors.
Note that the inline conditional assignment triggers several errors, but I personally don't mind a little bit of extra harassment for that sin 😄 
Fixes #69
> Allow for multiple variable assignments

- CHANGELOG.md
- HM/ruleset.xml
In 5e3e9eb2bc0ce0d99b469cd94d23f3bcaa66ea98, I re-allowed multiple arguments on a line after a WPCS change, but in my copy-🍝, I only fixed this for PHPCS, and not PHPCBF. This fixes #62 by adjusting this in all places.
You can test this by adding `example.php` locally (see below) and running `vendor/bin/phpcbf --standard=HM/ruleset.xml example.php`. The code should remain unchanged.
```php
<?php
add_filter( 'determine_current_user', function ( $user ) {
return 1;
} );
```
> Turn off ContentAfterOpenBracket and CloseBracketLine for phpcbf

- CHANGELOG.md
- packages/eslint-config-humanmade/index.js
- packages/eslint-config-humanmade/package.json
Adds the React Hooks eslin plugin, as well as pegging the general React rules at a higher version.
Fixes #189
Fixes #194
> Add ESLInt Rules of Hooks ruleset

- CHANGELOG.md
- HM/ruleset.xml
- readme.md
Removing the last of the PHPCS settings that were preventing projects from setting their own values effectively. This makes our ruleset a more effective Standard in that we're no longer making assumptions for end users.
Also added examples of the values that may be set  per-project to the readme.
Resolves #191
> Remove Final PHPCS settings

- CHANGELOG.md
- HM/ruleset.xml
Allows for theme-specific filenames with underscores in them.
Fixes #55
> Allow for theme filenames when sniffing filename

- packages/eslint-config-humanmade/index.js
Our current rules enforce comma-dangle globally, which includes function arguments despite that not being standard in JavaScript (and an error in most versions of PHP). I propose we adapt our config for this rule to only require/apply the comma for non-function multiline situations.
> Do not enforce comma-dangle for function arguments

- CHANGELOG.md
- packages/stylelint-config/.stylelintrc.json
As mentioned in #193, the WordPress `selector-class pattern` does not allow for BEM, and the ID pattern is also unnecessarily restrictive.
This PR:
- Modifies the `selector-class-pattern` rule to require BEM-type naming. See examples below.
- Removes the `selector-id-pattern` rule as we have no standard for naming ID.
cc @humanmade/frontend 
Passes:
```css
.something {}
.some-class {}
.anything-else__and--other-things {}
.blocky-mc-block-face {}
.block__element {}
.block__element--modifier {}
.long-block__long-element--long-modifier {}
```
Errors:
```css
.block__element__element {}
.block__element--modifier--modifier {}
.block--modifier--modifier {}
.block--modifier__element {}
```
You can play around with these examples here: https://regex101.com/r/pH8CMO/1
Fixes #193
> Adjust Stylelint class and ID selector patterns

- HM/ruleset.xml
The full stop flags in the Docs ruleset is nice for consistency, but generates a huge amount of noise and is generally has not other use. Removing it here to avoid the pain when people install 1.0
> Ignore the full stop rules for comments

- .travis.yml
PHP containers on Travis appear to use Node 8, which is end-of-life and throws errors on valid syntax within NPM dependencies. Testing Node code in specific Node environments avoids this issue of unexpected legacy Node running within PHP containers. (This appears to be the cause of the build error in #209)
> Test against a list of PHP and Node versions, and separate by language

- .travis.yml
We've been running Travis builds twice on PRs which is unnecessary, slow, and wastes potential concurrency on HM's Travis account. This limits branch runs to only run on master, and makes it so that runs only happen once on PRs.
> Limit Travis runs to master

- CHANGELOG.md
- packages/eslint-config-humanmade/fixtures/fail/component-jsx-parentheses.js
- packages/eslint-config-humanmade/fixtures/fail/jsx-boolean-value.jsx
- packages/eslint-config-humanmade/fixtures/fail/jsx-curly-newline.jsx
- packages/eslint-config-humanmade/fixtures/fail/semicolon.js
- packages/eslint-config-humanmade/fixtures/fail/variable-declaration.js
- packages/eslint-config-humanmade/fixtures/pass/component-jsx-parentheses.jsx
- packages/eslint-config-humanmade/fixtures/pass/jsdoc-inline-arrow.js
- packages/eslint-config-humanmade/fixtures/pass/jsx-boolean-value.jsx
- packages/eslint-config-humanmade/fixtures/pass/jsx-curly-newline.jsx
- packages/eslint-config-humanmade/fixtures/pass/semicolon.js
- packages/eslint-config-humanmade/index.js
- packages/eslint-config-humanmade/package.json
Per https://eslint.org/docs/rules/require-jsdoc this set of options appears to implement what was discussed in #157. Anonymous arrows are excluded from JSDoc requirements, while classes, function declarations, and methods all require documentation.
Fixes #157.
> Require JSDoc for functions other than anonymous arrows.

- packages/eslint-config-humanmade/index.js
When using the **full** `HM` ESLint coding standards ruleset, you have to sort props on any JSX element, or you will see a warning. This is great, I love it!
The PR where this was introduced is #195.
And the current version still has the rule just like in the PR:
https://github.com/humanmade/coding-standards/blob/229b6e932ac8a0468b385a44c2836ae6f77ac0e6/packages/eslint-config-humanmade/index.js#L124-L127
One thing that is odd with this, which is simply because of the default behavior of the `react/jsx-sort-props` rule, is that it is **case-sensitive**, meaning uppercase letters come before lowercase ones.
This means that I have to sort props like so:
```js
<Foo
solutionType={ solutionType }
solutions={ solutions }
/>
```
This feels unnatural to me, and changing this is can be done by …
> Make JSX props sorting case-insensitive

- CONTRIBUTING.md
This PR adds more thorough instructions for pushing and tagging a release.
> Improve deploy instructions

- packages/eslint-config-humanmade/fixtures/fail/import-order.js
- packages/eslint-config-humanmade/fixtures/pass/import-order.js
- packages/eslint-config-humanmade/index.js
This is a first pass for #84, making use of the already available [ESLint `import` plugin](https://github.com/benmosher/eslint-plugin-import/) (and **not** the [`sort-imports` rule](https://eslint.org/docs/rules/sort-imports)).
I decided to only pull in rules that are considered [errors](https://github.com/benmosher/eslint-plugin-import/blob/master/config/errors.js):
* [`import/default`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/default.md)
* [`import/export`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/export.md)
* [`import/named`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/named.md)
* [`import/namespace`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/namespace.md)
* …
> ESLint: Add and configure import plugin

- README.md
Got caught out by this - if you don't use the scoped module name it doesn't work (although I think it used to pre-1.0.0)
The readme within the eslint pacakge is actually correct, but this version hasn't reached the [npm page](https://www.npmjs.com/package/@humanmade/eslint-config) which is still not right.
> Update the readme to use scoped module name for eslint in example

- composer.json
When using Composer 2, the CI build breaks due to a plugin (API) conflict in the [PHP_CodeSniffer Composer Installer](https://github.com/Dealerdirect/phpcodesniffer-composer-installer) package, as seen [here](https://travis-ci.org/github/humanmade/coding-standards/jobs/738939458#L261).
This PR bumps the dependency to its most recent version, [0.7.0](https://github.com/Dealerdirect/phpcodesniffer-composer-installer/releases/tag/v0.7.0), that comes with support for Composer 2.
> Update PHP_CodeSniffer Composer Installer package to support Composer 2

- HM/Sniffs/Performance/SlowMetaQuerySniff.php
- tests/fixtures/pass/meta-queries.php
The code introduced in #181 breaks for queries that include the `relation` element.
Example:
```
'meta_query' => [
'relation' => 'OR', // <-- This triggers a false-positive.
[ ... ],
],
```
The reason is that the current code only expects (nested) arrays inside the meta query element, or a "first-order" query.
This PR adds support for the `relation` element, by skipping over it, if found. Please see also the added fixtures.
> Support 'relation' element in meta query sniff.

- composer.json
> Backport PHP_CodeSniffer Installer package upgrade to v0.8 branch

- CHANGELOG.md
- HM/ruleset.xml
> Exclude doc param alignment rules

- CHANGELOG.md
- composer.json
Realized we needed to backfill the 1.1.1 release...
Also fills in the date for 1.1.2 assuming we're releasing that relaxation of phpdoc alignment today, and adds a composer test script alias to make the testing path discoverable via avenues other than contributing.md
> Retroactively update changelog

- packages/eslint-config-humanmade/package.json
Draft: This is a WIP, adding the multiple ESLint versions to `peerDependencies` may cause issues with the install instructions: `npx install-peerdeps --dev @humanmade/eslint-config@latest` and needs further testing
Right now if installing `@humanmade/eslint-config` v1.0.0 with ESLint v6 or v7 installed the following message is observed:
> `npm WARN @humanmade/eslint-config@1.0.0 requires a peer of eslint@^5.10.0 but none is installed. You must install peer dependencies yourself.`
Adding v6 and v7 to the `peerDependencies` will resolve this
> Support ESLint v6 & v7 in `peerDependencies`

- HM/Sniffs/PHP/IssetSniff.php
- tests/FixtureTests.php
- tests/fixtures/fail/isset.php
- tests/fixtures/fail/isset.php.json
- tests/fixtures/pass/isset.php
This PR adds a new sniff, `HM.PHP.Isset` that throws an error for `isset` calls with more than one argument, as per request in #142.
I wasn't sure if wanted to make this an error, or just a warning. Looking at existing warnings and errors, I think we are rather inconsistent. Some Layout and opinionated sniffs throw errors, while others just warn about stuff that makes perfect sense to follow.
Thoughts?
Do we want to make this a part of `HM-Minimum`?
> #142 - Add new Isset sniff

- HM-Minimum/ruleset.xml
We renamed the clean_html function from whitelist_html in https://github.com/humanmade/clean-html/issues/6 but didn't update the standards to reflect.
> Update custom escaping functions for clean_html

- packages/stylelint-config/.stylelintrc.json
- packages/stylelint-config/package-lock.json
- packages/stylelint-config/package.json
I am having some issues with HM Linter bot flagging style issues, but I'm not getting the same errors locally. and I'm a little stumped by it. I don't know for sure, but i think committing the package lock file could help ensure this isn't caused by mismatched versions. 
The actual problem is this: https://github.com/humanmade/HM-Playbook/pull/200, and the errors flagged are related to the rule `function-calc-no-invalid`. Yet its not happening locally. Looks like this was a bug in stylelint when used with sass files, and it was [fixed a year ago](https://github.com/stylelint/stylelint/pull/4046). This makes me suspect that this could be caused by a version mismatch, and therefore may be fixed by committing the lockfile.
> Update `@humanmade/stylelint-config` in preparation for v2 release

- HM/Sniffs/Layout/OrderSniff.php
- tests/fixtures/pass/use-order.php
The error which is reported:
(
[message] => use found on line 48, but require was declared on line 7. Statements should be ordered `namespace`, `use`, `const`, `require`, then code.
[source] => HM.Layout.Order.WrongOrder
[listener] => HM\Sniffs\Layout\OrderSniff
[severity] => 5
[fixable] =>
)
It should be possible to `use` a trait within a class, without triggering the warning for a top-level namespace `use` statement.
> Ignore "use" within "class" in OrderSniff

- composer.json
This resolves an issue with Travis CI where the `dealerdirect/phpcodesniffer-composer-installer` package is blocked from installing because its not included in the `allow-plugins` config and the PHP jobs in Travis CI are failing
> Add `dealerdirect/phpcodesniffer-composer-installer` to `allow-plugins` in `composer.json`

- .travis.yml
- package-lock.json
- package.json
- packages/eslint-config-humanmade/package-lock.json
- packages/eslint-config-humanmade/package.json
- packages/eslint-config-humanmade/readme.md
- packages/stylelint-config/package-lock.json
- packages/stylelint-config/package.json
- packages/stylelint-config/readme.md
[@tfrommen suggested in another PR that we regenerate the `package-lock.json` to use version 2 as a separate Pull Request to keep the size of the change down. ](https://github.com/humanmade/coding-standards/pull/275#discussion_r809226824)
One thing raised in that conversation was that we need to ensure backwards compatibility with Node 12 and NPM 6 as this is what is used by the Altis Build pipeline. [I'd just like to be clear that npm 6 does indeed support lockfile v2 so this change should be fine. ](https://github.blog/2021-02-02-npm-7-is-now-generally-available/#changes-to-the-lockfile).
> Increase NPM version requirement and regenerate package lockfiles

- .travis.yml
- composer.json
- phpunit.xml.dist
- tests/AllSniffs.php
- tests/bootstrap.php
This change means later versions of PHPCS 3.x can be used, rather than just 3.5. Version 3.7 is required for the sniffs to run on PHP 8.1 without triggering deprecated warnings.
In addition version 3.6 added support for PHP 8 languages features, and 3.7 added support for 8.1 language features.
WPCS and PHPUnit both need to be updated so the tests run on later PHP versions without errors. PHPUnit 7 needs to be used because the base test class in PHPCS that's used for the tests in this library doesn't support PHPUnit 8 ([info here](https://github.com/squizlabs/PHP_CodeSniffer/issues/3490)), hence the use of the ` --ignore-platform-reqs` and `--no-configuration` flags when installing and running the tests on PHP 8 and 8.1.
Todo:
> Update PHPCS to support PHP 8+

- packages/stylelint-config/package-lock.json
- packages/stylelint-config/package.json
This contribute towards #274 by upgrading the official WP package used for configuration and upgrading stylelint to 14.2 which was required by the WP package update. This fixes some deprecation notices that show up downstream in projects
> Update stylelint and the official WP package
